[env]
CARGO_NET_GIT_FETCH_WITH_CLI = "true"
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER = { value = "scripts/aarch64-unknown-linux-musl-linker", relative = true, force = true }
CC_aarch64_unknown_linux_musl = { value = "scripts/aarch64-unknown-linux-musl-linker", relative = true, force = true }
AR_aarch64_unknown_linux_musl = { value = "scripts/aarch64-unknown-linux-musl-ar", relative = true, force = true }

[net]
git-fetch-with-cli = true

[target.aarch64-apple-darwin]
linker = "/usr/bin/clang"
runner = "scripts/codesign-runner"

[target.aarch64-unknown-linux-musl]
linker = "scripts/aarch64-unknown-linux-musl-linker"
